const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const app = fs.readFileSync(path.join(root, 'app.js'), 'utf8');
const css = fs.readFileSync(path.join(root, 'styles.css'), 'utf8');
assert.match(html,/data-panel="pitchTracking"/, 'separate Pitch Tracking section must be present');
assert.match(html,/id="activePitcherSelect"/, 'live scorer must provide an active pitcher selector');
assert.match(html,/id="pitcherTrackingSummary"/, 'pitcher statistics area must be present');
assert.match(html,/id="pitchEventLog"/, 'permanent pitch log must be present');
assert.match(html,/id="downloadPitchLogBtn"/, 'pitch log CSV export must be present');
assert.match(app,/pitchLog:\[\],nextPitchSeq:1,pitchLogVersion:1/, 'scoring state must include a permanent pitch log');
assert.match(app,/appendPitchLogEvent\(type,before,after/, 'every pitch button must append a pitch event');
assert.match(app,/countBefore:\{balls:/, 'pitch events must retain the count before the pitch');
assert.match(app,/countAfter:\{balls:/, 'pitch events must retain the count after the pitch');
assert.match(app,/pitcherKey:/, 'pitch events must retain pitcher identity');
assert.match(app,/computePitcherTracking\(\)/, 'pitcher totals must be computed from pitch and play records');
assert.match(app,/s\.pitches\+\+/, 'total pitches must be counted');
assert.match(app,/s\.balls\+\+/, 'balls must be counted');
assert.match(app,/s\.strikes\+\+/, 'strikes must be counted');
assert.match(app,/s\.fouls\+\+/, 'fouls must be counted');
assert.match(app,/s\.walks\+\+/, 'walks must be counted');
assert.match(app,/s\.hitBatters\+\+/, 'hit batters must be counted');
assert.match(app,/version:VERSION_NUMBER/, 'saved game files must identify the current version');
assert.match(css,/\.pitcher-tracking-summary/, 'Pitch Tracking section must have responsive styling');
console.log('permanent pitch tracking tests passed');
