const fs=require('fs');
const assert=require('assert');
const html=fs.readFileSync('index.html','utf8');
const css=fs.readFileSync('styles.css','utf8');
const app=fs.readFileSync('app.js','utf8');
const pkg=JSON.parse(fs.readFileSync('package.json','utf8'));
const manifest=JSON.parse(fs.readFileSync('manifest.webmanifest','utf8'));

assert.equal(pkg.version,'28.0.0');
assert.equal(manifest.short_name,'Scorecard V28');
assert.match(html,/Version 28/);
assert.match(html,/id="pitchConsoleTitle">Live Game Center/);
assert.match(html,/class="scoreboard-card broadcast-scorebox"/);
assert(html.indexOf('class="scoreboard-card broadcast-scorebox"')>html.indexOf('<section class="pitch-console"'),'broadcast scorebox must live inside the pitch console');
assert(html.indexOf('class="scoreboard-card broadcast-scorebox"')<html.indexOf('class="abs-challenge-card broadcast-abs-challenge"'),'ABS tracker must follow the primary scorebox information');
assert(html.indexOf('class="abs-challenge-card broadcast-abs-challenge"')<html.indexOf('</div>\n\n        <div class="active-pitcher-row"'),'ABS tracker must be consolidated inside the broadcast scorebox');
for(const id of ['scoreAwayAbbr','scoreHomeAbbr','scoreAwayName','scoreHomeName','scoreAwayRuns','scoreHomeRuns','inningLabel','outsLabel','gameStatusLabel','base1','base2','base3','ballCount','strikeCount','currentBatterName','currentPitcherName','onDeckName','inHoleName'])assert(html.includes(`id="${id}"`),`missing ${id}`);
assert.match(css,/broadcast-scorebox\.scoreboard-card/);
assert.match(css,/broadcast-count\.count-display strong\{font-size:clamp\(1\.55rem,3vw,2\.2rem\)/,'count must be substantially smaller than the prior oversized count');
assert.match(css,/@media \(max-width:430px\)[\s\S]*broadcast-scorebox/,'mobile scorebox rules missing');
assert.match(app,/function teamScoreboxAbbreviation/);
assert.match(app,/function compactInningLabel/);
assert.match(app,/onDeckIndex=\(index\+1\)%LINEUP_ROWS/);
assert.match(app,/inHoleIndex=\(index\+2\)%LINEUP_ROWS/);
assert.match(app,/scoreAwayAbbr/);
assert.match(app,/compactInningLabel\(\)/);
assert.match(app,/const VERSION_NUMBER = 28/);
assert.match(app,/LEGACY_AUTOSAVE_KEYS/,'Version 27.2 autosave migration must remain available');
console.log('Version 28 broadcast-style Live Game Center tests passed');
