const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const app=fs.readFileSync(path.join(root,'app.js'),'utf8');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const css=fs.readFileSync(path.join(root,'styles.css'),'utf8');
assert.match(html,/Version 27/,'visible app version must be 26');
assert.match(app,/const VERSION_NUMBER = 27/,'saved games must identify Version 27');
assert.match(app,/MLB_TEAM_COLOR_RECORDS/,'all MLB home-team palettes must be present');
assert.match(app,/scorecardPaletteForHomeTeam/,'PDF palette must resolve from the home team');
assert.match(app,/themedScorecardBackground\(false,classicPdfPalette\)/,'completed PDF must use clean boxes');
assert.match(app,/removeTraditionalScoringGuides/,'completed PDF must erase plus signs and 2x3 counters');
assert.match(app,/top-2\.6,26\.5,8\.8/,'computer-generated PDF notation must be larger and bold');
assert.match(html,/id="downloadBlankPdfBtn"/,'blank PDF control must be visible');
assert.match(html,/id="blankPdfWithGuidesBtn"/,'blank PDF must offer traditional guides');
assert.match(html,/id="blankPdfCleanBtn"/,'blank PDF must offer clean boxes');
assert.match(app,/exportBlankClassicPdf\(true\)/,'traditional-guide option must be wired');
assert.match(app,/exportBlankClassicPdf\(false\)/,'clean-box option must be wired');
assert.match(css,/\.pa-select\{appearance:none[\s\S]*font-size:1\.12rem[\s\S]*font-weight:900/,'online scoring codes must be large and bold');
assert.doesNotMatch(app,/plays\.length\?plays\.map\(playNotation\)\.join\(" \/ "\):"\+"/,'computer print cells must not add plus signs');
assert.match(html,/styles\.css\?v=27.2-mobile-roster-save/,'Version 27 CSS must be cache-busted');
assert.match(html,/app\.js\?v=27.2-mobile-roster-save/,'Version 27 JS must be cache-busted');
console.log('Version 24 inherited PDF theme and clean-box tests passed');
